#UUID conf
spring.data.mongodb.uuid-representation=standard
#AUDIT CONF
spring.data.mongodb.auto-index-creation=false
spring.data.mongodb.uri=mongodb://localhost:27017/condomio
spring.data.mongodb.database=condomio
