#UUID conf
spring.mongodb.uuid-representation=standard
#AUDIT CONF
spring.mongodb.auto-index-creation=false
spring.mongodb.uri=${SPRING_MONGODB_URI:${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/condomio}}
spring.mongodb.database=${SPRING_MONGODB_DATABASE:${SPRING_DATA_MONGODB_DATABASE:condomio}}
